# Copyright (C) 2018 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
#
---

# Se sube el archivo de config de nginx
- name: Upload nginx.conf configuration
  template: src=templates/etc/nginx.conf.j2 dest=/etc/nginx/nginx.conf

# Se sube el archivo de configuracion de omnileads para nginx
- name: Create of ominicontacto.conf
  template: src=templates/etc/ominicontacto.conf dest=/etc/nginx/conf.d/ominicontacto.conf owner={{ usuario }} group={{ usuario }}
  tags: postinstall

# Se pasan los certificados creados en kamailio a la carpeta nginx_certs
- name: Copy of the certificates in nginx
  copy: "src={{ kamailio_location }}/etc/certs/{{ item }} dest={{ install_prefix }}nginx_certs/ remote_src=yes"
  with_items:
    - cert.pem
    - key.pem
  tags: postinstall

# Se copia el certificado del servidor de llaves, para poder registrar la instancia de OML
- name: Copy register server certificate in default location
  copy: src=/var/tmp/ansible/cert dest={{ install_prefix }} owner={{ usuario }} group={{ usuario }}
  tags: postinstall

# Se crea el archivo .ini de uwsgi. Para mas info revisar documentacion de uwsgi
- name: Create of oml_uwgsi.ini script
  template: src=templates/run/oml_uwsgi.ini dest={{ install_prefix }}run/oml_uwsgi.ini mode=755 owner={{ usuario }} group={{ usuario }}
  tags: postinstall

# Se ejecuta una funcion de sql que hizo ale, esto es para los reportes
- name: Add queuelog trigger to database
  shell: psql -c '\i {{ install_prefix }}ominicontacto/reportes_app/sql/plperl/replace_insert_queue_log_ominicontacto_queue_log.sql'
  environment:
    PGPASSWORD: "{{ postgres_password }}"
  become: true
  become_user: "{{ usuario }}"
  become_method: su
  tags: ['never','postinstall']

# Se sube el script de backup-restore
- name: Generate extra scripts
  template: src=templates/bin/{{ item.src }} dest={{ install_prefix }}bin/{{ item.dest }} owner={{ usuario }} group={{ usuario }} mode=755
  with_items:
    - { src: backup-restore.sh, dest: backup-restore.sh }
    - { src: conversor.sh, dest: conversor.sh }
    - { src: reinstall_addons.sh, dest: reinstall_addons.sh }
  tags: postinstall

# Se ejecuta el script reinstal_addons.sh el cual detecta si un addon está instalado en el OML para asi volver a ejecutar los scripts de instalacion de dichos addons y queden funcionales.
- name: Execute reinstall_addons.sh script
  command: "{{ install_prefix }}bin/reinstall_addons.sh"
  tags: postinstall

- name: Increase number of connections accepted by UNIX sockets
  command: sysctl -w net.core.somaxconn=2048
  tags: postinstall

- name: Write the number of max connections in /etc/sysctl.conf
  blockinfile:
    path: /etc/sysctl.conf
    insertafter: EOF
    state: present
    block: |
      net.core.somaxconn=2048
  tags: postinstall

# Se inicia y habilita el servicio
- name: Start the omnileads-daemon service
  systemd: name=omnileads state=restarted enabled=yes daemon_reload=yes
  tags: postinstall

# Se borra la supervision en php que viene desde 1.2.X para atras
- name: Erase files related to php supervision
  file: state=absent path={{ item }}
  with_items:
    - /etc/nginx/conf.d/supervision.conf
    - "{{ install_prefix }}Omnisup"
  tags: ['never','postinstall']

# Starteo y habilito nginx
- name: Reload of nginx
  service: name=nginx state=reloaded enabled=yes
  tags: ['postinstall','kamailio']

# Se cambia el ownership de este path para que no tire el error 500 cuando se quiere acceder a la parte de subir audios
- name: Change ownership of /var/lib/nginx/tmp/
  file: state=directory owner={{ usuario }} group={{ usuario }} path=/var/lib/nginx recurse=yes

# Se crea el script de desinstalacion de OML
- name: Creation of Omnileads uninstall script
  template: src=templates/bin/oml-uninstall.sh dest=/usr/sbin/oml-uninstall mode=755 owner=root group=root
  tags: postinstall
