# Copyright (C) 2018 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
#
---

# Se sube el archivo de config de nginx
- name: Upload nginx.conf configuration
  template: src=templates/etc/nginx.conf.j2 dest=/etc/nginx/nginx.conf
  become: true
  become_method: sudo

# Se sube el archivo de configuracion de omnileads para nginx
- name: Create of ominicontacto.conf
  template: src=templates/etc/ominicontacto.conf.j2 dest=/etc/nginx/conf.d/ominicontacto.conf owner={{ usuario }} group={{ usuario }}
  become: true
  become_method: sudo
  tags: postinstall

# Se pasan los certificados creados en kamailio a la carpeta nginx_certs
- name: Copy of the certificates in nginx (aio)
  copy: "src={{ kamailio_location }}/etc/certs/{{ item }} dest={{ install_prefix }}nginx_certs/ remote_src=yes"
  with_items:
      - cert.pem
      - key.pem
  become: true
  become_method: sudo
  tags: kamailio
  when: cluster == 0

# Se pasan los certificados creados en kamailio a la carpeta nginx_certs
- name: Copy the certificates from host to omniapp server (cluster)
  copy: src=/var/tmp/ansible/{{ item }} dest={{ install_prefix }}nginx_certs/
  with_items:
    - ca_cert.pem
    - cert.pem
    - key.pem
  when: cluster != 0

# Se crea el archivo .ini de uwsgi. Para mas info revisar documentacion de uwsgi
- name: Create of oml_uwgsi.ini script
  template: src=templates/run/oml_uwsgi.ini dest={{ install_prefix }}run/oml_uwsgi.ini mode=755 owner={{ usuario }} group={{ usuario }}

# Se crea el archivo .ini de uwsgi. Para mas info revisar documentacion de uwsgi
- name: Create of ominicontacto_app.ini script
  template: src=templates/run/ominicontacto_app.ini dest={{ install_prefix }}run/ominicontacto_app.ini mode=755 owner={{ usuario }} group={{ usuario }}

# Se crea el arhivo de systemd para omnileads daemon
- name: Create of omnileads service
  template: src=templates/omnileads.service dest=/etc/systemd/system/omnileads.service owner=root group=root mode=650
  become: true
  become_method: sudo
  tags: postinstall

# Se inicia y habilita el servicio
- name: Start the omnileads-daemon service
  systemd: name=omnileads state=restarted enabled=yes daemon_reload=yes
  become: true
  become_method: sudo
  when: desarrollo == 0

# El concatenate.sh es un script chamullero que sirve para poner en un solo archivo (voip.cert) el certificado de CA concatenado con el cert de nodo
# Así evitamos la advertencia de seguridad de los browsers.
- name: Creation of voip.cert file
  template: src=templates/bin/concatenate.sh dest={{ install_prefix }}bin/concatenate.sh mode=755
  ignore_errors: yes
  tags: kamailio
  become: true
  become_method: sudo

- shell: "bash concatenate.sh chdir={{ install_prefix }}bin"
  tags: kamailio
  become: true
  become_method: sudo
  become_user: "{{ usuario }}"

# Se ejecuta una funcion de sql que hizo ale, esto es para los reportes
- name: Add queuelog trigger to database
  shell: psql -U {{ postgres_user}} -h {{ database_fqdn }} -d {{ postgres_database }} -c '\i {{ install_prefix }}ominicontacto/reportes_app/sql/plpython/replace_insert_queue_log_ominicontacto_queue_log.sql'
  become: true
  environment:
    PGPASSWORD: "{{ postgres_password }}"
  tags: ['never','postinstall']
  become_method: sudo

# Este script sirve para hacer comandos de manage.py sin necesidad de activar virualenv primero
- name: Generate manage.sh script
  template: src=templates/bin/manage.sh.j2 dest={{ install_prefix }}bin/manage.sh owner={{ usuario }} group={{ usuario }} mode=755

# Se sube el script de backup-restore
- name: Generate backup-restore.sh script
  template: src=templates/bin/backup-restore.sh.j2 dest={{ install_prefix }}bin/backup-restore.sh owner={{ usuario }} group={{ usuario }} mode=755

# Se inicia y habilita el servicio
- name: Reload the omnileads-daemon service
  systemd: name=omnileads state=reloaded enabled=yes daemon_reload=yes
  become: true
  become_method: sudo
  tags: ['postinstall','changeip']
  when: desarrollo == 0
