# Copyright (C) 2018 Freetech Solutions

# This file is part of OMniLeads

# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see http://www.gnu.org/licenses/.
#
---

##################
## Centos tasks ##
##################

# Se excluye postgres de la lista de repositorios base y updates
- name: Exclude postgres in list of repositories
  ini_file: "path=/etc/yum.repos.d/CentOS-Base.repo section={{ item }} option=exclude no_extra_spaces=yes value=postgres* state=present"
  with_items:
    - base
    - updates
  become: true
  become_method: sudo
  when: ansible_os_family == "RedHat"

# Se instala el repo de postgresql9.6
- name: Install of postgresql-9.6 repository
  yum: "name={{ postgresql_url }} state=present validate_certs=no "
  become: yes
  become_method: sudo
  when: ansible_os_family == "RedHat"

  #Se instalan todos los paquetes de postgresql96
- name: Install of postgresql-9.6 (centos)
  yum: name={{ item }} state=present
  with_items:
    - postgresql96*
    - python-psycopg2.x86_64
  become: yes
  become_method: sudo
  when: ansible_os_family == "RedHat"

############################
## Ubuntu / Debian tasks ##
###########################

- name: Add the postgresql repository key (ubuntu )
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc validate_certs=no state=present
  become: true
  become_method: sudo
  when: ansible_distribution == "Ubuntu"

- name: Download postgresql-9.6 repository
  apt_repository: repo="deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main" filename=pgdg state=present update_cache=yes
  become: true
  become_method: sudo
  when: ansible_distribution == "Ubuntu"

#Se intala postgresql debian
- name: Install of postgresql 9.6
  apt: name={{ item }} state=present
  with_items:
    - postgresql-plpython-9.6
    - postgresql-9.6
    - python-psycopg2
  when: ansible_os_family == "Debian"
